<!-- Comic-Ink Redo v3.1:Copyright 2024:Phillip Emmons:06-14-23 -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>CoMiCs InK</title>
  <link rel="icon" type="image/x-icon" href="/img/fav/favicon.ico">
  <!-- Latest Bootstrap compiled and minified CSS library-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>

  <!-- Latest Bootstrap compiled JavaScript library-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

  <script src="js/jsFinal.js"></script>

  <!-- https://datatables.net/ -->
  <link href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">
  <link href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.dataTables.min.css" rel="stylesheet">

  <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
  <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js"></script>

  <style>
    @import url("css/styleFinal.css");
  </style>
</head>

<body id="toTop">
  <div id="bgRight"></div>
  <div id="bgLeft"></div>

  <a href="#main-content" class="btn btn-skip" aria-label="Go To Main Content">Go To Main Content</a>

  <!--
  <header>
    <div id="wrapper-header">
      <div class="title">
        <img src="img/banner.png" alt="Comic books are a publication that consists of comic art in the form of sequential juxtaposed panels that represent individual scenes." />
      </div>
    </div>
  </header>
-->
  <!-- Hero Part -->
  <header>
    <div class="container">
      <div class="row justify-content-center bg-img-home m-5">
        <div class="col-xl-7 col-lg-7 col-md-12 py-5 my-5 text-center">
            <h1 class="text-red-white">Comic Ink</h1>
            <p class= "shadow-text-area">Comic books are a publication that consists of comic art in the form of sequential juxtaposed panels that represent individual scenes.</p>
            <p class="text-red-white">Discover More</p>
        </div>
      </div>
    </div>
  </header>

  <!-- https://getbootstrap.com/docs/5.0/components/navbar/-->
  <nav class="navbar navbar-expand-md bg-body-tertiary" aria-label="main menu">
    <div class="container-fluid">

      <button class="navbar-toggler my-2 border border-2 border-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

        <span class="navbar-brand fw-bold">
          <img width="60" height="60" class="d-inline-block" src='./img/pow.png' alt="Comic Ink Logo">
          Comics Ink
        </span>